// GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand.
// Regenerated on every build (prebuild); kept honest by version.test.mjs.

/**
 * This transpiler's package version — the toolchain stamp (PRETRANSPILED_ARTIFACTS_SPEC §4.4).
 * The version pins the entire per-file transform chain and its configs; the
 * runtime compares it (plus `toolchainHash`) against `index.json`'s
 * `toolchain.version` and ignores all artifacts on mismatch.
 */
export const TRANSPILER_VERSION = '0.8.0';

/**
 * The preset whose chain this package replicates. Part of the stamp: a v1
 * transpiler covers the `react` preset only (the immediately.run v1 default).
 */
export const PRESET_NAME = 'react';
